name: Assign Issue

on:
  issues:
    tyes:
      - opened

jobs:
  auto-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue to team member
        uses: actions-ecosystem/action-add-assignees@v1
        with:
          assignees: shianwen123
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
